<h1>Créer un nouveau groupe</h1>
<section>
    <form class="form-container" method="POST" action="index.php?route=create-group">
        <label for="group-name">Nom du groupe</label>
        <input type="text" name="group-name" id="group-name" required>
        
        <h2>Ajouter des membres</h2>
        <table>
            <thead>
                <tr>
                    <th>Contact</th>
                    <th>Ajouter</th>
                </tr>
            </thead>
            <tbody>
                <?php if (!empty($contacts)) : ?>
                    <?php foreach ($contacts as $contact) : ?>
                        <tr>
                            <td><?= htmlspecialchars($contact['username'], ENT_QUOTES, 'UTF-8') ?></td>
                            <td>
                                <input type="checkbox" name="members[]" value="<?= htmlspecialchars($contact['id'], ENT_QUOTES, 'UTF-8') ?>">
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php else : ?>
                    <tr>
                        <td colspan="2">Aucun contact trouvé</td>
                    </tr>
                <?php endif; ?>
            </tbody>
        </table>
        
        <a href="index.php?route=add-contact">
            <p>Ajouter un nouveau contact</p>
            <i class="fas fa-plus"></i>
        </a>
        
        <button type="submit" class="button">Créer le groupe</button>
    </form>
</section>